name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      # Use pnpm ci to install dependencies based on the pnpm-lock.yaml without updating it
      run: pnpm ci
    - name: Build the project
      run: pnpm run build --if-present
